### ISSUE TITLE
Add ${MINICONDA_ML_ROOT}/bin to PATH before `pip` commands

### ISSUE THREAD

**Issue by davedavemckay** [hpc-uk/build-instructions#105]
Hi @mbareford,
Running through this today I found between the "Setup initial environment" and "Install ML packages" sections of build_miniconda3_cirrus_gpu.md I got `command not found` errors for `pip` and `python`.
I added:
`export PATH=${MINICONDA_ML_ROOT}/bin:$PATH`
to my version.
This also prevents pip-installing the packages onto the wrong virtual environment in case `pip` is found, but is from another location.
Cheers

**Comment by mbareford** [comment]
This issue concerns the pytorch/tensorflow pages. However, the issue no longer applies as a consequence of restructuring the modules to match more closely the setup on ARCHER2. Previously, gpu, pytorch and tensorflow were built as separate miniconda3 environments. Now, the gpu module has been replaced by a different miniconda3 environment called `mpi4py/3.1.3-ompi-gpu`. PyTorch and TensorFlow are now virtual environments whose module files load the `mpi4py` module. The build instructions for those ml modules include `export PATH=${PYTHONUSERBASE}/bin:${PATH}`.

**Comment by aturner-epcc** [comment]
@mbareford Does this mean that this issue can be closed with no further action required?

**Comment by mbareford** [comment]
@aturner-epcc Yes, that's correct.

**Comment by aturner-epcc** [comment]
Thanks @mbareford Closing this issue now.
