### ISSUE TITLE
Disk space requirements

### ISSUE THREAD

**Issue by davedavemckay** [hpc-uk/build-instructions#124]
Hi,
Could disk space requirements be added to the byenv build instructions please? My student has attempted to install pytorch (and will also require tensorflow) and has exceeded his quota. It would be useful to know the disk requirements so we can request an increased quota for him.
Thanks,
Dave

**Comment by aturner-epcc** [comment]
@davedavemckay Thanks for the note. My first though is that going through all the install instructions in the repo and working out disk space requirements is not a trivial undertaking and so I do not think we can do this. One way you could get an idea of the size is to install it on your laptop and then look at how much space it takes on disk.

**Comment by davedavemckay** [comment]
@aturner-epcc OK, no problem. I was thinking @mbareford might still have this, not expecting anyone to repeat the risk.
It looks like a clean install of miniconda3+pytorch+tensorflow+horovod is 7.5GB.
Not the lite-est!
Dave

**Comment by aturner-epcc** [comment]
Glad you got some estimate on this. I will close this one.
