### ISSUE TITLE
epw is not included

### ISSUE THREAD

**Issue by byornski** [hpc-uk/build-instructions#95]
It would be useful if you could add EPW to the build as it is not built by default. It is a build target but not included in the "all" target. It can be built by adding

make epw

after the initial make all.

**Comment by aturner-epcc** [comment]
@byornski Thank you for your comment/request. Can you provide a bit more information on what you are asking for here? Which of the software build instructions in the repo are you referring to and on which system?

**Comment by byornski** [comment]
This would be for quantum espresso on archer2 specifically. "epw.x" does not seem to be included in the standard build steps provided here, but does actually build easily and installs to the same folder. This lets you perform interpolation of electronic structure calculations, but is rather computationally intensive itself.  It is also highly parallel and probably something that should be built for large HPC systems (https://docs.epw-code.org/doc/Benchmarks.html)

**Comment by aturner-epcc** [comment]
@byornski I have added QE 6.8 build instructions for ARCHER2 including EPW so have closed this issue
